name: Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upload backend files
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "backend/*,!backend/.env"
        target: "/var/www/wardrobe/backend"
        overwrite: true

    - name: Restart backend
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/wardrobe/backend
          npm install --production
          pm2 restart wardrobe-backend
